name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        compiler: [gcc, clang]
        build_type: [debug, release]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install system packages
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
          sudo apt-get -y update &&
          sudo apt-get install python3 pip g++-12 clang-14 flex bison libfl-dev binutils libc++-14-dev libc++abi-14-dev
        fi

    - name: Install conan and set venv
      run: python3 -m venv .venv;
           source .venv/bin/activate;
           echo PATH=$PATH >> $GITHUB_ENV;
           pip install conan==2.12.1;

    - name: Install conan requirements
      run: >
        conan profile detect --force;
        conan install .
        -pr=ci/profiles/${{ matrix.os }}/${{ matrix.compiler }}_${{ matrix.build_type }}.profile
        --output-folder=build
        --build=missing

    - name: Configure CMake
      run: >
        cmake . -B build --preset conan-${{ matrix.build_type }}

    - name: Build
      run:
        cmake --build build -j

    - name: Test
      if: ${{ matrix.build_type == 'debug' }}
      run: ctest --output-on-failure --test-dir build --no-tests=error
