name: CMake with multiple configs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: victorbaldin56/linux_dev:9296cfaf74bb3462f2130eed8db62094d723a565

    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
        build_type: [debug, release]

    steps:
    - uses: actions/checkout@v4

    - name: Install conan requirements
      run: >
        conan profile detect --force;
        conan install .
        -pr:a=ci/profiles/${{ matrix.compiler }}_${{ matrix.build_type }}.profile
        --output-folder=build
        --build=missing
        -c tools.system.package_manager:mode=install
        --lockfile-partial

    - name: Configure CMake
      run: >
        cmake . -B build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run:
        cmake --build build -j

    - name: Test
      run: ctest --output-on-failure --test-dir build -j --no-tests=error

    - name: Benchmark
      if: ${{ matrix.build_type == 'release' }}
      run: |
        export APP=${{ github.workspace }}/build/driver/triangles
        pushd ${{ github.workspace }}/tests/e2e/bench/
        bash benchmark.sh
